modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vscreate"
version = "${version}"
displayName = "Create x Valkyrien Skies Template"
authors = ["fluffy", "potato", "ewoudje"]
description = '''
A template mod for Create x Valkyrien Skies mods.
'''
logoFile = "icon.png"

[[dependencies.vscreate]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vscreate]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vscreate]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vscreate]]
modId = "create"
mandatory = true
versionRange = "${create_version}"
ordering = "NONE"
side = "BOTH"
